# Generated by Django 2.2.15 on 2020-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('discordpingformatter', '0002_fleetcomm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Discord', 'Discord'), ('Slack', 'Slack')], default='Discord', help_text='Is this a Discord or Slack webhook?', max_length=7)),
                ('channel', models.CharField(help_text='Name of the channel this webhook posts to', max_length=64, unique=True)),
                ('url', models.CharField(help_text='URL of this webhook, e.g. https://discordapp.com/api/webhooks/123456/abcdef', max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, default=None, help_text='You can add notes about this webhook here if you want', null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this webhook is active or not')),
                ('restricted_to_group', models.ManyToManyField(blank=True, help_text='Restrict ping right to this webhook to one or more groups.', related_name='webhook_require_groups', to='auth.Group')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'default_permissions': (),
            },
        ),
    ]
