# Generated by Django 2.2.15 on 2020-09-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordpingformatter', '0003_webhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetcomm',
            options={'default_permissions': (), 'verbose_name': 'Fleet Comm', 'verbose_name_plural': 'Fleet Comms'},
        ),
    ]
