# Generated by Django 2.2.15 on 2020-09-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordpingformatter', '0004_auto_20200911_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='channel',
            new_name='name',
        ),
    ]
