# Generated by Django 2.2.15 on 2020-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordpingformatter', '0005_auto_20200911_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDoctrine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name to identify this soctrine', max_length=64, unique=True)),
                ('notes', models.TextField(blank=True, default=None, help_text='You can add notes about this doctrine here if you want', null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this doctrine is enabled or not')),
            ],
            options={
                'verbose_name': 'Fleet Doctrine',
                'verbose_name_plural': 'Fleet Doctrines',
                'default_permissions': (),
            },
        ),
    ]
