# Generated by Django 2.2.15 on 2020-09-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordpingformatter", "0011_webhook_is_embedded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleettype",
            name="embed_color",
            field=models.CharField(
                blank=True, help_text="Hightlight color for the embed", max_length=7
            ),
        ),
    ]
