# Generated by Django 2.2.15 on 2020-09-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordpingformatter", "0012_auto_20200911_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordpingtargets",
            name="restricted_to_group",
            field=models.ManyToManyField(
                help_text="Restrict the right to ping this Discord group to one or more groups.",
                related_name="discord_role_require_groups",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="restricted_to_group",
            field=models.ManyToManyField(
                help_text="Restrict ping right to this webhook to one or more groups.",
                related_name="webhook_require_groups",
                to="auth.Group",
            ),
        ),
    ]
